FROM node:18 AS build

WORKDIR /app/ClientApp
COPY ./src/DSTest.Api/ClientApp /app/ClientApp/

RUN npm ci
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/ClientApp/dist/client-app /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
